

CREATE TABLE `tb_cmd_cfg` (
  `SEQ` bigint(22) DEFAULT NULL,
  `FUNC_ID` varchar(40) DEFAULT NULL,
  `CFG_KEY` varchar(40) DEFAULT NULL,
  `MEMO` varchar(100) DEFAULT NULL,
  `EXEC_CMD` longtext,
  `ENABLE` varchar(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `tb_param_cfg` (
  `FUNC_ID` varchar(20) NOT NULL DEFAULT '',
  `PARAM_TYPE` varchar(20) NOT NULL DEFAULT '',
  `PARAM_NAME` varchar(40) NOT NULL DEFAULT '',
  `PARAM_DESC` varchar(200) DEFAULT NULL,
  `PARAM_FORMAT` varchar(40) DEFAULT NULL,
  `PARAM_VAL_EXPR` text,
  `ENABLE` varchar(1) DEFAULT NULL,
  `REPLACE_ORDER` bigint(22) DEFAULT NULL,
  PRIMARY KEY (`FUNC_ID`,`PARAM_TYPE`,`PARAM_NAME`),
  UNIQUE KEY `IDX_TB_PARAM_CFG` (`FUNC_ID`,`PARAM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `tb_execcmd` (
  `DATATIME` varchar(8) NOT NULL DEFAULT '',
  `FUNC_ID` varchar(40) NOT NULL DEFAULT '',
  `SEQ` bigint(22) NOT NULL DEFAULT '0',
  `MEMO` varchar(100) DEFAULT NULL,
  `EXEC_CMD` longtext,
  `FLAG` bigint(22) DEFAULT NULL,
  `ERR_MSG` text,
  `START_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `EXEC_ELAPSED` bigint(22) DEFAULT NULL,
  `EXEC_DATE` datetime DEFAULT NULL,
  `BUSINESS_PARAM` varchar(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`DATATIME`,`FUNC_ID`,`SEQ`,`BUSINESS_PARAM`)
) ENGINE